import scrapy
from scrapy.item import Field
from scrapy.loader.processors import MapCompose

def name_cleaner(value):
    return value.replace('\n','').strip()
def seed_cleaner(value):
    return value.replace('&nbsp','').replace('Seeded:', '').strip()

class AustralianOpenItem(scrapy.Item):
    tournament = Field()
    tournament_phase = scrapy.Field()
    calendar_year = scrapy.Field()
    player1_name = Field(input_processor=MapCompose(name_cleaner))
    player1_surname = Field(input_processor=MapCompose(name_cleaner))
    player1_country = Field()
    player1_seed = Field(input_processor=MapCompose(seed_cleaner))
    player1_total_sets = Field()
    player1_1st_set = Field()
    player1_2nd_set = Field()
    player1_3rd_set = Field()
    player1_4th_set = Field()
    player1_5th_set = Field()
    p1_total_points_won = Field()
    p1_total_games_won = Field()
    p1_max_points_row = Field()
    p1_max_games_row = Field()
    p1_tiebreaks_won = Field()
    p1_servgames_won = Field()
    p1_aces = Field()
    p1_doublefaults = Field()
    p1_1stserve_success = Field()
    p1_1stserve_pwon = Field()
    p1_2ndserve_pwon = Field()
    p1_breakpoints_won = Field()
    player2_name = Field()
    player2_surname = Field()
    player2_country = Field()
    player2_seed = Field(input_processor=MapCompose(seed_cleaner))
    player2_total_sets = Field()
    player2_1st_set = Field()
    player2_2nd_set = Field()
    player2_3rd_set = Field()
    player2_4th_set = Field()
    player2_5th_set = Field()
    p2_total_points_won = Field()
    p2_total_games_won = Field()
    p2_max_points_row = Field()
    p2_max_games_row = Field()
    p2_tiebreaks_won = Field()
    p2_servgames_won = Field()
    p2_aces = Field()
    p2_doublefaults = Field()
    p2_1stserve_success = Field()
    p2_1stserve_pwon = Field()
    p2_2ndserve_pwon = Field()
    p2_breakpoints_won = Field()
