# TOURNAMENT PAGE
game_details_list_xpath = "//div[@class='tc-order-of-play__inner-card-wrapper']"
tournament_phase_xpath = ".//div[@class='tc-match__info']/span/text()"

# GAME PAGE
game_href_xpath = ".//div[@class='tc-match__cta ']//a/@href"
# Player1
player1_name_xpath = ".//div[@class='tc-match-details__match-card-player'][1]//div[@class='tc-player__name']//a/text()"
player1_surname_xpath = ".//div[@class='tc-match-details__match-card-player'][1]//div[@class='tc-player__name--surname']//a/text()"
player1_country_xpath = ".//div[@class='tc-match-details__match-card-player'][1]//div[@class='tc-player__country']/text()"
player1_seed_xpath = ".//div[@class='tc-match-details__match-card-player'][1]//div[@class='tc-player-seeding']/text()"
player1_total_sets_xpath = ".//div[@class='tc-match-details__match-card-player'][1]//div[@class='match-card-score__stats--set -total']/text()"
p1_total_points_won_xpath = ".//*[text()='Total Points Won']/preceding::div[1]/text()"
p1_total_games_won_xpath = ".//*[text()='Total Games Won']/preceding::div[1]/text()"
p1_max_points_row_xpath = ".//*[text()='Max Points in a row']/preceding::div[1]/text()"
p1_max_games_row_xpath = ".//*[text()='Max Games in a row']/preceding::div[1]/text()"
p1_tiebreaks_won_xpath = ".//*[text()='Tie Breaks Won']/preceding::div[1]/text()"
p1_servgames_won_xpath = ".//*[text()='Service games won']/preceding::div[1]/text()"
p1_aces_xpath = ".//*[text()='Aces']/preceding::div[1]/text()"
p1_doublefaults_xpath = ".//*[text()='Double Faults']/preceding::div[1]/text()"
p1_1stserve_success_xpath = ".//*[text()='First Serve Successful']/preceding::div[1]/text()"
p1_1stserve_pwon_xpath = ".//*[text()='First Serve points won']/preceding::div[1]/text()"
p1_2ndserve_pwon_xpath = ".//*[text()='Second Serve points won']/preceding::div[1]/text()"
p1_breakpoints_won_xpath = ".//*[text()='Break points won']/preceding::div[1]/text()"
p1_sets_list_xpath = ".//div[@class='tc-match-details__match-card-score__stats']//div[@class='match-card-score__stats-sets-container']/div[contains(@class, 'match-card-score__stats--set')]/text()"
# Player2
player2_name_xpath = ".//div[@class='tc-match-details__match-card-player'][2]//div[@class='tc-player__name']//a/text()"
player2_surname_xpath = ".//div[@class='tc-match-details__match-card-player'][2]//div[@class='tc-player__name--surname']//a/text()"
player2_country_xpath = ".//div[@class='tc-match-details__match-card-player'][2]//div[@class='tc-player__country']/text()"
player2_seed_xpath = ".//div[@class='tc-match-details__match-card-player'][2]//div[@class='tc-player-seeding']/text()"
player2_total_sets_xpath = ".//div[@class='tc-match-details__match-card-player'][2]//div[@class='match-card-score__stats--set -total']/text()"
p2_total_points_won_xpath = ".//*[text()='Total Points Won']/following::div[1]/text()"
p2_total_games_won_xpath = ".//*[text()='Total Games Won']/following::div[1]/text()"
p2_max_points_row_xpath = ".//*[text()='Max Points in a row']/following::div[1]/text()"
p2_max_games_row_xpath = ".//*[text()='Max Games in a row']/following::div[1]/text()"
p2_tiebreaks_won_xpath = ".//*[text()='Tie Breaks Won']/following::div[1]/text()"
p2_servgames_won_xpath = ".//*[text()='Service games won']/following::div[1]/text()"
p2_aces_xpath = ".//*[text()='Aces']/following::div[1]/text()"
p2_doublefaults_xpath = ".//*[text()='Double Faults']/following::div[1]/text()"
p2_1stserve_success_xpath = ".//*[text()='First Serve Successful']/following::div[1]/text()"
p2_1stserve_pwon_xpath = ".//*[text()='First Serve points won']/following::div[1]/text()"
p2_2ndserve_pwon_xpath = ".//*[text()='Second Serve points won']/following::div[1]/text()"
p2_breakpoints_won_xpath = ".//*[text()='Break points won']/following::div[1]/text()"
p2_sets_list_xpath = ".//div[@class='tc-match-details__match-card-score__stats']//div[@class='match-card-score__stats-sets-container -away']/div[contains(@class, 'match-card-score__stats--set')]/text()"
